services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer

    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      - APACHE_PORT=${APACHE_PORT}
      - APACHE_IP_BINDING=${APACHE_IP_BINDING}
      - SKIP_DOMAIN_VALIDATION=${SKIP_DOMAIN_VALIDATION}
      - TALK_PORT=${TALK_PORT}
      - COLLABORA_SECCOMP_DISABLED=${COLLABORA_SECCOMP_DISABLED}
      - AIO_ADDITIONAL_HOSTS=${NEXTCLOUD_DOMAIN}:${NEXTCLOUD_HOST_IP}

    extra_hosts:
      - "nextcloud.local.cloud:192.168.0.53"

    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
